//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Model.XSD
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NalogZaPlacanje", Namespace="http://schemas.datacontract.org/2004/07/Shared.Model.XSD")]
    public partial class NalogZaPlacanje : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDNalogaZaPlacanjeField;
        
        private string IDPorukeField;
        
        private string DuznikField;
        
        private string SvrhaPlacanjaField;
        
        private string PrimalacField;
        
        private System.DateTime DatumNalogaField;
        
        private System.DateTime DatumValuteField;
        
        private string RacunDuznikaField;
        
        private int ModelZaduzenjaField;
        
        private string PozivNaBrZaduzenjaField;
        
        private string RacunPoveriocaField;
        
        private int ModelOdobrenjaField;
        
        private double PozivNaBrOdobrenjaField;
        
        private double IznosField;
        
        private string OznakaValuteField;
        
        private bool HitnoField;
        
        private string StatusField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDNalogaZaPlacanje
        {
            get
            {
                return this.IDNalogaZaPlacanjeField;
            }
            set
            {
                this.IDNalogaZaPlacanjeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string IDPoruke
        {
            get
            {
                return this.IDPorukeField;
            }
            set
            {
                this.IDPorukeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Duznik
        {
            get
            {
                return this.DuznikField;
            }
            set
            {
                this.DuznikField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string SvrhaPlacanja
        {
            get
            {
                return this.SvrhaPlacanjaField;
            }
            set
            {
                this.SvrhaPlacanjaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Primalac
        {
            get
            {
                return this.PrimalacField;
            }
            set
            {
                this.PrimalacField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.DateTime DatumNaloga
        {
            get
            {
                return this.DatumNalogaField;
            }
            set
            {
                this.DatumNalogaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.DateTime DatumValute
        {
            get
            {
                return this.DatumValuteField;
            }
            set
            {
                this.DatumValuteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string RacunDuznika
        {
            get
            {
                return this.RacunDuznikaField;
            }
            set
            {
                this.RacunDuznikaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int ModelZaduzenja
        {
            get
            {
                return this.ModelZaduzenjaField;
            }
            set
            {
                this.ModelZaduzenjaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string PozivNaBrZaduzenja
        {
            get
            {
                return this.PozivNaBrZaduzenjaField;
            }
            set
            {
                this.PozivNaBrZaduzenjaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string RacunPoverioca
        {
            get
            {
                return this.RacunPoveriocaField;
            }
            set
            {
                this.RacunPoveriocaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public int ModelOdobrenja
        {
            get
            {
                return this.ModelOdobrenjaField;
            }
            set
            {
                this.ModelOdobrenjaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public double PozivNaBrOdobrenja
        {
            get
            {
                return this.PozivNaBrOdobrenjaField;
            }
            set
            {
                this.PozivNaBrOdobrenjaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public double Iznos
        {
            get
            {
                return this.IznosField;
            }
            set
            {
                this.IznosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string OznakaValute
        {
            get
            {
                return this.OznakaValuteField;
            }
            set
            {
                this.OznakaValuteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public bool Hitno
        {
            get
            {
                return this.HitnoField;
            }
            set
            {
                this.HitnoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=16)]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PorukaOOdobrenju", Namespace="http://schemas.datacontract.org/2004/07/Shared.Model.XSD")]
    public partial class PorukaOOdobrenju : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DatumValuteField;
        
        private string IDPorukeField;
        
        private string IDPorukeNalogaField;
        
        private int IDPorukeOOdobrenjuField;
        
        private double IznosField;
        
        private string ObracunskiRacunBankePoveriocaField;
        
        private string SWIFTBankePoveriocaField;
        
        private string SifraValuteField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DatumValute
        {
            get
            {
                return this.DatumValuteField;
            }
            set
            {
                this.DatumValuteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDPoruke
        {
            get
            {
                return this.IDPorukeField;
            }
            set
            {
                this.IDPorukeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDPorukeNaloga
        {
            get
            {
                return this.IDPorukeNalogaField;
            }
            set
            {
                this.IDPorukeNalogaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDPorukeOOdobrenju
        {
            get
            {
                return this.IDPorukeOOdobrenjuField;
            }
            set
            {
                this.IDPorukeOOdobrenjuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Iznos
        {
            get
            {
                return this.IznosField;
            }
            set
            {
                this.IznosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObracunskiRacunBankePoverioca
        {
            get
            {
                return this.ObracunskiRacunBankePoveriocaField;
            }
            set
            {
                this.ObracunskiRacunBankePoveriocaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SWIFTBankePoverioca
        {
            get
            {
                return this.SWIFTBankePoveriocaField;
            }
            set
            {
                this.SWIFTBankePoveriocaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SifraValute
        {
            get
            {
                return this.SifraValuteField;
            }
            set
            {
                this.SifraValuteField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RTGSNalog", Namespace="http://schemas.datacontract.org/2004/07/Shared.Model.XSD")]
    public partial class RTGSNalog : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDRTGSNalogaField;
        
        private string IDPorukeField;
        
        private string SWIFTBankaDuznikaField;
        
        private string ObracunskiRacunBankeDuznikaField;
        
        private string SWIFTBankaPoveriocaField;
        
        private string ObracunskiRacunBankePoveriocaField;
        
        private string DuznikField;
        
        private string SvrhaPlacanjaField;
        
        private string PrimalacField;
        
        private System.DateTime DatumNalogaField;
        
        private System.DateTime DatumValuteField;
        
        private string RacunDuznikaField;
        
        private double ModelZaduzenjaField;
        
        private string PozivNaBrZaduzenjaField;
        
        private string RacunPoveriocaField;
        
        private double ModelOdobrenjaField;
        
        private string PozivNaBrOdobrenjaField;
        
        private double IznosField;
        
        private string SifraValuteField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDRTGSNaloga
        {
            get
            {
                return this.IDRTGSNalogaField;
            }
            set
            {
                this.IDRTGSNalogaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string IDPoruke
        {
            get
            {
                return this.IDPorukeField;
            }
            set
            {
                this.IDPorukeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SWIFTBankaDuznika
        {
            get
            {
                return this.SWIFTBankaDuznikaField;
            }
            set
            {
                this.SWIFTBankaDuznikaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ObracunskiRacunBankeDuznika
        {
            get
            {
                return this.ObracunskiRacunBankeDuznikaField;
            }
            set
            {
                this.ObracunskiRacunBankeDuznikaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SWIFTBankaPoverioca
        {
            get
            {
                return this.SWIFTBankaPoveriocaField;
            }
            set
            {
                this.SWIFTBankaPoveriocaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ObracunskiRacunBankePoverioca
        {
            get
            {
                return this.ObracunskiRacunBankePoveriocaField;
            }
            set
            {
                this.ObracunskiRacunBankePoveriocaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Duznik
        {
            get
            {
                return this.DuznikField;
            }
            set
            {
                this.DuznikField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string SvrhaPlacanja
        {
            get
            {
                return this.SvrhaPlacanjaField;
            }
            set
            {
                this.SvrhaPlacanjaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Primalac
        {
            get
            {
                return this.PrimalacField;
            }
            set
            {
                this.PrimalacField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public System.DateTime DatumNaloga
        {
            get
            {
                return this.DatumNalogaField;
            }
            set
            {
                this.DatumNalogaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public System.DateTime DatumValute
        {
            get
            {
                return this.DatumValuteField;
            }
            set
            {
                this.DatumValuteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string RacunDuznika
        {
            get
            {
                return this.RacunDuznikaField;
            }
            set
            {
                this.RacunDuznikaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public double ModelZaduzenja
        {
            get
            {
                return this.ModelZaduzenjaField;
            }
            set
            {
                this.ModelZaduzenjaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string PozivNaBrZaduzenja
        {
            get
            {
                return this.PozivNaBrZaduzenjaField;
            }
            set
            {
                this.PozivNaBrZaduzenjaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string RacunPoverioca
        {
            get
            {
                return this.RacunPoveriocaField;
            }
            set
            {
                this.RacunPoveriocaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public double ModelOdobrenja
        {
            get
            {
                return this.ModelOdobrenjaField;
            }
            set
            {
                this.ModelOdobrenjaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string PozivNaBrOdobrenja
        {
            get
            {
                return this.PozivNaBrOdobrenjaField;
            }
            set
            {
                this.PozivNaBrOdobrenjaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public double Iznos
        {
            get
            {
                return this.IznosField;
            }
            set
            {
                this.IznosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string SifraValute
        {
            get
            {
                return this.SifraValuteField;
            }
            set
            {
                this.SifraValuteField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PorukaOZaduzenju", Namespace="http://schemas.datacontract.org/2004/07/Shared.Model.XSD")]
    public partial class PorukaOZaduzenju : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDPorukeOZaduzenjuField;
        
        private string IDPPorukeField;
        
        private string SWIFTBankeDuznikaField;
        
        private string ObracunskiRacunBankeDuznikaField;
        
        private string IDPorukeNalogaField;
        
        private System.DateTime DatumValuteField;
        
        private double IznosField;
        
        private string SifraValuteField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDPorukeOZaduzenju
        {
            get
            {
                return this.IDPorukeOZaduzenjuField;
            }
            set
            {
                this.IDPorukeOZaduzenjuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string IDPPoruke
        {
            get
            {
                return this.IDPPorukeField;
            }
            set
            {
                this.IDPPorukeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SWIFTBankeDuznika
        {
            get
            {
                return this.SWIFTBankeDuznikaField;
            }
            set
            {
                this.SWIFTBankeDuznikaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ObracunskiRacunBankeDuznika
        {
            get
            {
                return this.ObracunskiRacunBankeDuznikaField;
            }
            set
            {
                this.ObracunskiRacunBankeDuznikaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string IDPorukeNaloga
        {
            get
            {
                return this.IDPorukeNalogaField;
            }
            set
            {
                this.IDPorukeNalogaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.DateTime DatumValute
        {
            get
            {
                return this.DatumValuteField;
            }
            set
            {
                this.DatumValuteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public double Iznos
        {
            get
            {
                return this.IznosField;
            }
            set
            {
                this.IznosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string SifraValute
        {
            get
            {
                return this.SifraValuteField;
            }
            set
            {
                this.SifraValuteField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ZahtevZaDobijanjeIzvoda", Namespace="http://schemas.datacontract.org/2004/07/Shared.Model.XSD")]
    public partial class ZahtevZaDobijanjeIzvoda : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDZZDIField;
        
        private string BrRacunaField;
        
        private System.Nullable<System.DateTime> DatumField;
        
        private double RedniBrPresekaField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDZZDI
        {
            get
            {
                return this.IDZZDIField;
            }
            set
            {
                this.IDZZDIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string BrRacuna
        {
            get
            {
                return this.BrRacunaField;
            }
            set
            {
                this.BrRacunaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<System.DateTime> Datum
        {
            get
            {
                return this.DatumField;
            }
            set
            {
                this.DatumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public double RedniBrPreseka
        {
            get
            {
                return this.RedniBrPresekaField;
            }
            set
            {
                this.RedniBrPresekaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NalogZaGrupnoPlacanje", Namespace="http://schemas.datacontract.org/2004/07/Shared.Model.XSD")]
    public partial class NalogZaGrupnoPlacanje : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDNalogaZaGrupnoPlacanjeField;
        
        private string IDPorukeField;
        
        private string SWIFTBankeDuznikaField;
        
        private string ObracunskiRacunBankeDuznikaField;
        
        private string SWIFTBankePoveriocaField;
        
        private string ObracunskiRacunBankePoveriocaField;
        
        private double UkupanIznosField;
        
        private string SifraValuteField;
        
        private System.DateTime DatumValuteField;
        
        private System.DateTime DatumField;
        
        private string StatusField;
        
        private Shared.Model.XSD.StavkeGrupnogPlacanja StavkeGrupnogPlacanjaField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDNalogaZaGrupnoPlacanje
        {
            get
            {
                return this.IDNalogaZaGrupnoPlacanjeField;
            }
            set
            {
                this.IDNalogaZaGrupnoPlacanjeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string IDPoruke
        {
            get
            {
                return this.IDPorukeField;
            }
            set
            {
                this.IDPorukeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SWIFTBankeDuznika
        {
            get
            {
                return this.SWIFTBankeDuznikaField;
            }
            set
            {
                this.SWIFTBankeDuznikaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ObracunskiRacunBankeDuznika
        {
            get
            {
                return this.ObracunskiRacunBankeDuznikaField;
            }
            set
            {
                this.ObracunskiRacunBankeDuznikaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SWIFTBankePoverioca
        {
            get
            {
                return this.SWIFTBankePoveriocaField;
            }
            set
            {
                this.SWIFTBankePoveriocaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ObracunskiRacunBankePoverioca
        {
            get
            {
                return this.ObracunskiRacunBankePoveriocaField;
            }
            set
            {
                this.ObracunskiRacunBankePoveriocaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public double UkupanIznos
        {
            get
            {
                return this.UkupanIznosField;
            }
            set
            {
                this.UkupanIznosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string SifraValute
        {
            get
            {
                return this.SifraValuteField;
            }
            set
            {
                this.SifraValuteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.DateTime DatumValute
        {
            get
            {
                return this.DatumValuteField;
            }
            set
            {
                this.DatumValuteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public System.DateTime Datum
        {
            get
            {
                return this.DatumField;
            }
            set
            {
                this.DatumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public Shared.Model.XSD.StavkeGrupnogPlacanja StavkeGrupnogPlacanja
        {
            get
            {
                return this.StavkeGrupnogPlacanjaField;
            }
            set
            {
                this.StavkeGrupnogPlacanjaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="StavkeGrupnogPlacanja", Namespace="http://schemas.datacontract.org/2004/07/Shared.Model.XSD", ItemName="Stavke")]
    public class StavkeGrupnogPlacanja : System.Collections.Generic.List<Shared.Model.XSD.StavkaGrupnogPlacanja>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StavkaGrupnogPlacanja", Namespace="http://schemas.datacontract.org/2004/07/Shared.Model.XSD")]
    public partial class StavkaGrupnogPlacanja : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDStavkeGrupnogPlacanjaField;
        
        private string IDNalogaZaPlacanjeField;
        
        private string DuznikField;
        
        private string SvrhaPlacanjaField;
        
        private string PrimalacField;
        
        private System.DateTime DatumNalogaField;
        
        private string RacunDuznikaField;
        
        private int ModelZaduzenjaField;
        
        private string PozivNaBrZaduzenjaField;
        
        private string RacunPoveriocaField;
        
        private int ModelOdobrenjaField;
        
        private string PozivNaBrOdobrenjaField;
        
        private double IznosField;
        
        private string SifraValuteField;
        
        private int IDNalogaZaGrupnoPlacanjeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDStavkeGrupnogPlacanja
        {
            get
            {
                return this.IDStavkeGrupnogPlacanjaField;
            }
            set
            {
                this.IDStavkeGrupnogPlacanjaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string IDNalogaZaPlacanje
        {
            get
            {
                return this.IDNalogaZaPlacanjeField;
            }
            set
            {
                this.IDNalogaZaPlacanjeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Duznik
        {
            get
            {
                return this.DuznikField;
            }
            set
            {
                this.DuznikField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string SvrhaPlacanja
        {
            get
            {
                return this.SvrhaPlacanjaField;
            }
            set
            {
                this.SvrhaPlacanjaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Primalac
        {
            get
            {
                return this.PrimalacField;
            }
            set
            {
                this.PrimalacField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.DateTime DatumNaloga
        {
            get
            {
                return this.DatumNalogaField;
            }
            set
            {
                this.DatumNalogaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string RacunDuznika
        {
            get
            {
                return this.RacunDuznikaField;
            }
            set
            {
                this.RacunDuznikaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int ModelZaduzenja
        {
            get
            {
                return this.ModelZaduzenjaField;
            }
            set
            {
                this.ModelZaduzenjaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string PozivNaBrZaduzenja
        {
            get
            {
                return this.PozivNaBrZaduzenjaField;
            }
            set
            {
                this.PozivNaBrZaduzenjaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string RacunPoverioca
        {
            get
            {
                return this.RacunPoveriocaField;
            }
            set
            {
                this.RacunPoveriocaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public int ModelOdobrenja
        {
            get
            {
                return this.ModelOdobrenjaField;
            }
            set
            {
                this.ModelOdobrenjaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string PozivNaBrOdobrenja
        {
            get
            {
                return this.PozivNaBrOdobrenjaField;
            }
            set
            {
                this.PozivNaBrOdobrenjaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public double Iznos
        {
            get
            {
                return this.IznosField;
            }
            set
            {
                this.IznosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string SifraValute
        {
            get
            {
                return this.SifraValuteField;
            }
            set
            {
                this.SifraValuteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public int IDNalogaZaGrupnoPlacanje
        {
            get
            {
                return this.IDNalogaZaGrupnoPlacanjeField;
            }
            set
            {
                this.IDNalogaZaGrupnoPlacanjeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Faktura", Namespace="http://schemas.datacontract.org/2004/07/Shared.Model.XSD")]
    public partial class Faktura : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDFaktureField;
        
        private string IDPorukeField;
        
        private string NazivDobavljacaField;
        
        private string AdresaDobavljacaField;
        
        private string PIBDobavljacaField;
        
        private string NazivKupcaField;
        
        private string AdresaKupcaField;
        
        private string PIBKupcaField;
        
        private double BrRacunaField;
        
        private System.DateTime DatumRacunaField;
        
        private double VrednostRobeField;
        
        private double VrednostUslugaField;
        
        private double UkupnoRobaIUslugeField;
        
        private double UkupanRabatField;
        
        private double UkupanPorezField;
        
        private string OznakaValuteField;
        
        private double IznosZaUplatuField;
        
        private string UplataNaRacunField;
        
        private System.DateTime DatumValuteField;
        
        private Shared.Model.XSD.ListaStavkiFakture StavkeFaktureField;
        
        private string StatusField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDFakture
        {
            get
            {
                return this.IDFaktureField;
            }
            set
            {
                this.IDFaktureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string IDPoruke
        {
            get
            {
                return this.IDPorukeField;
            }
            set
            {
                this.IDPorukeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NazivDobavljaca
        {
            get
            {
                return this.NazivDobavljacaField;
            }
            set
            {
                this.NazivDobavljacaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string AdresaDobavljaca
        {
            get
            {
                return this.AdresaDobavljacaField;
            }
            set
            {
                this.AdresaDobavljacaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PIBDobavljaca
        {
            get
            {
                return this.PIBDobavljacaField;
            }
            set
            {
                this.PIBDobavljacaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string NazivKupca
        {
            get
            {
                return this.NazivKupcaField;
            }
            set
            {
                this.NazivKupcaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string AdresaKupca
        {
            get
            {
                return this.AdresaKupcaField;
            }
            set
            {
                this.AdresaKupcaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string PIBKupca
        {
            get
            {
                return this.PIBKupcaField;
            }
            set
            {
                this.PIBKupcaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public double BrRacuna
        {
            get
            {
                return this.BrRacunaField;
            }
            set
            {
                this.BrRacunaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public System.DateTime DatumRacuna
        {
            get
            {
                return this.DatumRacunaField;
            }
            set
            {
                this.DatumRacunaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public double VrednostRobe
        {
            get
            {
                return this.VrednostRobeField;
            }
            set
            {
                this.VrednostRobeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public double VrednostUsluga
        {
            get
            {
                return this.VrednostUslugaField;
            }
            set
            {
                this.VrednostUslugaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public double UkupnoRobaIUsluge
        {
            get
            {
                return this.UkupnoRobaIUslugeField;
            }
            set
            {
                this.UkupnoRobaIUslugeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public double UkupanRabat
        {
            get
            {
                return this.UkupanRabatField;
            }
            set
            {
                this.UkupanRabatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public double UkupanPorez
        {
            get
            {
                return this.UkupanPorezField;
            }
            set
            {
                this.UkupanPorezField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string OznakaValute
        {
            get
            {
                return this.OznakaValuteField;
            }
            set
            {
                this.OznakaValuteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public double IznosZaUplatu
        {
            get
            {
                return this.IznosZaUplatuField;
            }
            set
            {
                this.IznosZaUplatuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string UplataNaRacun
        {
            get
            {
                return this.UplataNaRacunField;
            }
            set
            {
                this.UplataNaRacunField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public System.DateTime DatumValute
        {
            get
            {
                return this.DatumValuteField;
            }
            set
            {
                this.DatumValuteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public Shared.Model.XSD.ListaStavkiFakture StavkeFakture
        {
            get
            {
                return this.StavkeFaktureField;
            }
            set
            {
                this.StavkeFaktureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ListaStavkiFakture", Namespace="http://schemas.datacontract.org/2004/07/Shared.Model.XSD", ItemName="Stavke")]
    public class ListaStavkiFakture : System.Collections.Generic.List<Shared.Model.XSD.StavkaFakture>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StavkaFakture", Namespace="http://schemas.datacontract.org/2004/07/Shared.Model.XSD")]
    public partial class StavkaFakture : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDStavkeField;
        
        private double RedniBrField;
        
        private string NazivRobeIliUslugeField;
        
        private double KolicinaField;
        
        private string JedinicaMereField;
        
        private double JedinicnaCenaField;
        
        private double VrednostField;
        
        private double ProcenatRabataField;
        
        private double IznosRabataField;
        
        private double UmanjenoZaRabatField;
        
        private double UkupanPorezField;
        
        private int IDFaktureField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDStavke
        {
            get
            {
                return this.IDStavkeField;
            }
            set
            {
                this.IDStavkeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double RedniBr
        {
            get
            {
                return this.RedniBrField;
            }
            set
            {
                this.RedniBrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NazivRobeIliUsluge
        {
            get
            {
                return this.NazivRobeIliUslugeField;
            }
            set
            {
                this.NazivRobeIliUslugeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public double Kolicina
        {
            get
            {
                return this.KolicinaField;
            }
            set
            {
                this.KolicinaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string JedinicaMere
        {
            get
            {
                return this.JedinicaMereField;
            }
            set
            {
                this.JedinicaMereField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public double JedinicnaCena
        {
            get
            {
                return this.JedinicnaCenaField;
            }
            set
            {
                this.JedinicnaCenaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public double Vrednost
        {
            get
            {
                return this.VrednostField;
            }
            set
            {
                this.VrednostField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public double ProcenatRabata
        {
            get
            {
                return this.ProcenatRabataField;
            }
            set
            {
                this.ProcenatRabataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public double IznosRabata
        {
            get
            {
                return this.IznosRabataField;
            }
            set
            {
                this.IznosRabataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public double UmanjenoZaRabat
        {
            get
            {
                return this.UmanjenoZaRabatField;
            }
            set
            {
                this.UmanjenoZaRabatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public double UkupanPorez
        {
            get
            {
                return this.UkupanPorezField;
            }
            set
            {
                this.UkupanPorezField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public int IDFakture
        {
            get
            {
                return this.IDFaktureField;
            }
            set
            {
                this.IDFaktureField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IBankaService")]
public interface IBankaService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankaService/ProveriBanku", ReplyAction="http://tempuri.org/IBankaService/ProveriBankuResponse")]
    string ProveriBanku();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankaService/sendMessageToFirm", ReplyAction="http://tempuri.org/IBankaService/sendMessageToFirmResponse")]
    void sendMessageToFirm(string firmName, string message);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankaService/NapraviNalogZaPrenos", ReplyAction="http://tempuri.org/IBankaService/NapraviNalogZaPrenosResponse")]
    void NapraviNalogZaPrenos(Shared.Model.XSD.NalogZaPlacanje nzp);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankaService/PrimiPorukuOOdobrenjuIRTGS", ReplyAction="http://tempuri.org/IBankaService/PrimiPorukuOOdobrenjuIRTGSResponse")]
    void PrimiPorukuOOdobrenjuIRTGS(Shared.Model.XSD.PorukaOOdobrenju odobrenje, Shared.Model.XSD.RTGSNalog nalog);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankaService/PrimiPorukuOZaduzenju", ReplyAction="http://tempuri.org/IBankaService/PrimiPorukuOZaduzenjuResponse")]
    void PrimiPorukuOZaduzenju(Shared.Model.XSD.PorukaOZaduzenju zaduzenje);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankaService/PredajPresekIzNaloga", ReplyAction="http://tempuri.org/IBankaService/PredajPresekIzNalogaResponse")]
    string PredajPresekIzNaloga(Shared.Model.XSD.ZahtevZaDobijanjeIzvoda zahtev);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankaService/NapraviNalogZaGrupnoPlacanje", ReplyAction="http://tempuri.org/IBankaService/NapraviNalogZaGrupnoPlacanjeResponse")]
    void NapraviNalogZaGrupnoPlacanje();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankaService/PrimiPorukuOOdobrenjuINalogZaGrupnoPlacanje", ReplyAction="http://tempuri.org/IBankaService/PrimiPorukuOOdobrenjuINalogZaGrupnoPlacanjeRespo" +
        "nse")]
    void PrimiPorukuOOdobrenjuINalogZaGrupnoPlacanje(Shared.Model.XSD.PorukaOOdobrenju odobrenje, Shared.Model.XSD.NalogZaGrupnoPlacanje nzgp);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IBankaServiceChannel : IBankaService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class BankaServiceClient : System.ServiceModel.ClientBase<IBankaService>, IBankaService
{
    
    public BankaServiceClient()
    {
    }
    
    public BankaServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public BankaServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BankaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BankaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string ProveriBanku()
    {
        return base.Channel.ProveriBanku();
    }
    
    public void sendMessageToFirm(string firmName, string message)
    {
        base.Channel.sendMessageToFirm(firmName, message);
    }
    
    public void NapraviNalogZaPrenos(Shared.Model.XSD.NalogZaPlacanje nzp)
    {
        base.Channel.NapraviNalogZaPrenos(nzp);
    }
    
    public void PrimiPorukuOOdobrenjuIRTGS(Shared.Model.XSD.PorukaOOdobrenju odobrenje, Shared.Model.XSD.RTGSNalog nalog)
    {
        base.Channel.PrimiPorukuOOdobrenjuIRTGS(odobrenje, nalog);
    }
    
    public void PrimiPorukuOZaduzenju(Shared.Model.XSD.PorukaOZaduzenju zaduzenje)
    {
        base.Channel.PrimiPorukuOZaduzenju(zaduzenje);
    }
    
    public string PredajPresekIzNaloga(Shared.Model.XSD.ZahtevZaDobijanjeIzvoda zahtev)
    {
        return base.Channel.PredajPresekIzNaloga(zahtev);
    }
    
    public void NapraviNalogZaGrupnoPlacanje()
    {
        base.Channel.NapraviNalogZaGrupnoPlacanje();
    }
    
    public void PrimiPorukuOOdobrenjuINalogZaGrupnoPlacanje(Shared.Model.XSD.PorukaOOdobrenju odobrenje, Shared.Model.XSD.NalogZaGrupnoPlacanje nzgp)
    {
        base.Channel.PrimiPorukuOOdobrenjuINalogZaGrupnoPlacanje(odobrenje, nzgp);
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ICentralnaBankaService")]
public interface ICentralnaBankaService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentralnaBankaService/AcceptRTGSAndSendMessages", ReplyAction="http://tempuri.org/ICentralnaBankaService/AcceptRTGSAndSendMessagesResponse")]
    void AcceptRTGSAndSendMessages(Shared.Model.XSD.RTGSNalog nalog);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentralnaBankaService/NalogZaGrupnoPlacanjeSendMessages", ReplyAction="http://tempuri.org/ICentralnaBankaService/NalogZaGrupnoPlacanjeSendMessagesRespon" +
        "se")]
    void NalogZaGrupnoPlacanjeSendMessages();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICentralnaBankaServiceChannel : ICentralnaBankaService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CentralnaBankaServiceClient : System.ServiceModel.ClientBase<ICentralnaBankaService>, ICentralnaBankaService
{
    
    public CentralnaBankaServiceClient()
    {
    }
    
    public CentralnaBankaServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CentralnaBankaServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CentralnaBankaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CentralnaBankaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void AcceptRTGSAndSendMessages(Shared.Model.XSD.RTGSNalog nalog)
    {
        base.Channel.AcceptRTGSAndSendMessages(nalog);
    }
    
    public void NalogZaGrupnoPlacanjeSendMessages()
    {
        base.Channel.NalogZaGrupnoPlacanjeSendMessages();
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IFirmaService")]
public interface IFirmaService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirmaService/GetData", ReplyAction="http://tempuri.org/IFirmaService/GetDataResponse")]
    string GetData(int value);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirmaService/SlanjeFakture", ReplyAction="http://tempuri.org/IFirmaService/SlanjeFaktureResponse")]
    XWS.Shared.Model.InterfejsiServisa.FakturaResponse SlanjeFakture(Shared.Model.XSD.Faktura faktura, string nazivFirme);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirmaService/ReturnMessageFromBank", ReplyAction="http://tempuri.org/IFirmaService/ReturnMessageFromBankResponse")]
    string ReturnMessageFromBank();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirmaService/AcceptMessageFromBank", ReplyAction="http://tempuri.org/IFirmaService/AcceptMessageFromBankResponse")]
    void AcceptMessageFromBank(string message);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirmaService/SaveCreatedInvoice", ReplyAction="http://tempuri.org/IFirmaService/SaveCreatedInvoiceResponse")]
    void SaveCreatedInvoice(Shared.Model.XSD.Faktura faktura);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirmaService/PrikaziFakture", ReplyAction="http://tempuri.org/IFirmaService/PrikaziFaktureResponse")]
    void PrikaziFakture(string nazivFirme);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirmaService/SendCreatedInvoice", ReplyAction="http://tempuri.org/IFirmaService/SendCreatedInvoiceResponse")]
    void SendCreatedInvoice(int idFakture);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirmaService/SendInvoiceProfile", ReplyAction="http://tempuri.org/IFirmaService/SendInvoiceProfileResponse")]
    void SendInvoiceProfile(Shared.Model.XSD.Faktura sourceInvoice);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirmaService/GetForCompanyAndStatus", ReplyAction="http://tempuri.org/IFirmaService/GetForCompanyAndStatusResponse")]
    Shared.Model.XSD.Faktura[] GetForCompanyAndStatus(XWS.Shared.Model.Firma firma, string status);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirmaService/NapraviNalogZaPrenosK", ReplyAction="http://tempuri.org/IFirmaService/NapraviNalogZaPrenosKResponse")]
    void NapraviNalogZaPrenosK(Shared.Model.XSD.NalogZaPlacanje nzp);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirmaService/NapraviNalogZaGrupnoPlacanjeK", ReplyAction="http://tempuri.org/IFirmaService/NapraviNalogZaGrupnoPlacanjeKResponse")]
    void NapraviNalogZaGrupnoPlacanjeK();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirmaService/PromeniStatusFakture", ReplyAction="http://tempuri.org/IFirmaService/PromeniStatusFaktureResponse")]
    void PromeniStatusFakture(int idFakture, string status);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFirmaService/ZahtevZaPresek", ReplyAction="http://tempuri.org/IFirmaService/ZahtevZaPresekResponse")]
    string ZahtevZaPresek(Shared.Model.XSD.ZahtevZaDobijanjeIzvoda zahtev);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IFirmaServiceChannel : IFirmaService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class FirmaServiceClient : System.ServiceModel.ClientBase<IFirmaService>, IFirmaService
{
    
    public FirmaServiceClient()
    {
    }
    
    public FirmaServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public FirmaServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public FirmaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public FirmaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string GetData(int value)
    {
        return base.Channel.GetData(value);
    }
    
    public XWS.Shared.Model.InterfejsiServisa.FakturaResponse SlanjeFakture(Shared.Model.XSD.Faktura faktura, string nazivFirme)
    {
        return base.Channel.SlanjeFakture(faktura, nazivFirme);
    }
    
    public string ReturnMessageFromBank()
    {
        return base.Channel.ReturnMessageFromBank();
    }
    
    public void AcceptMessageFromBank(string message)
    {
        base.Channel.AcceptMessageFromBank(message);
    }
    
    public void SaveCreatedInvoice(Shared.Model.XSD.Faktura faktura)
    {
        base.Channel.SaveCreatedInvoice(faktura);
    }
    
    public void PrikaziFakture(string nazivFirme)
    {
        base.Channel.PrikaziFakture(nazivFirme);
    }
    
    public void SendCreatedInvoice(int idFakture)
    {
        base.Channel.SendCreatedInvoice(idFakture);
    }
    
    public void SendInvoiceProfile(Shared.Model.XSD.Faktura sourceInvoice)
    {
        base.Channel.SendInvoiceProfile(sourceInvoice);
    }
    
    public Shared.Model.XSD.Faktura[] GetForCompanyAndStatus(XWS.Shared.Model.Firma firma, string status)
    {
        return base.Channel.GetForCompanyAndStatus(firma, status);
    }
    
    public void NapraviNalogZaPrenosK(Shared.Model.XSD.NalogZaPlacanje nzp)
    {
        base.Channel.NapraviNalogZaPrenosK(nzp);
    }
    
    public void NapraviNalogZaGrupnoPlacanjeK()
    {
        base.Channel.NapraviNalogZaGrupnoPlacanjeK();
    }
    
    public void PromeniStatusFakture(int idFakture, string status)
    {
        base.Channel.PromeniStatusFakture(idFakture, status);
    }
    
    public string ZahtevZaPresek(Shared.Model.XSD.ZahtevZaDobijanjeIzvoda zahtev)
    {
        return base.Channel.ZahtevZaPresek(zahtev);
    }
}
namespace XWS.Shared.Model.InterfejsiServisa
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FakturaResponse", Namespace="http://schemas.datacontract.org/2004/07/XWS.Shared.Model.InterfejsiServisa")]
    public partial class FakturaResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool SuccessField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }
}
namespace XWS.Shared.Model
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Firma", Namespace="http://schemas.datacontract.org/2004/07/XWS.Shared.Model")]
    public partial class Firma : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AdresaFirmeField;
        
        private int IDFirmeField;
        
        private string NazivFirmeField;
        
        private string PIBField;
        
        private long RacunField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdresaFirme
        {
            get
            {
                return this.AdresaFirmeField;
            }
            set
            {
                this.AdresaFirmeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDFirme
        {
            get
            {
                return this.IDFirmeField;
            }
            set
            {
                this.IDFirmeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NazivFirme
        {
            get
            {
                return this.NazivFirmeField;
            }
            set
            {
                this.NazivFirmeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PIB
        {
            get
            {
                return this.PIBField;
            }
            set
            {
                this.PIBField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Racun
        {
            get
            {
                return this.RacunField;
            }
            set
            {
                this.RacunField = value;
            }
        }
    }
}
