//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Model.XSD
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NalogZaPlacanje", Namespace="http://schemas.datacontract.org/2004/07/Shared.Model.XSD")]
    public partial class NalogZaPlacanje : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDNalogaZaPlacanjeField;
        
        private string IDPorukeField;
        
        private string DuznikField;
        
        private string SvrhaPlacanjaField;
        
        private string PrimalacField;
        
        private System.DateTime DatumNalogaField;
        
        private System.DateTime DatumValuteField;
        
        private string RacunDuznikaField;
        
        private double ModelZaduzenjaField;
        
        private string PozivNaBrZaduzenjaField;
        
        private string RacunPoveriocaField;
        
        private double ModelOdobrenjaField;
        
        private double PozivNaBrOdobrenjaField;
        
        private double IznosField;
        
        private string OznakaValuteField;
        
        private bool HitnoField;
        
        private string StatusField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDNalogaZaPlacanje
        {
            get
            {
                return this.IDNalogaZaPlacanjeField;
            }
            set
            {
                if ((this.IDNalogaZaPlacanjeField.Equals(value) != true))
                {
                    this.IDNalogaZaPlacanjeField = value;
                    this.RaisePropertyChanged("IDNalogaZaPlacanje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string IDPoruke
        {
            get
            {
                return this.IDPorukeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.IDPorukeField, value) != true))
                {
                    this.IDPorukeField = value;
                    this.RaisePropertyChanged("IDPoruke");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Duznik
        {
            get
            {
                return this.DuznikField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DuznikField, value) != true))
                {
                    this.DuznikField = value;
                    this.RaisePropertyChanged("Duznik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string SvrhaPlacanja
        {
            get
            {
                return this.SvrhaPlacanjaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SvrhaPlacanjaField, value) != true))
                {
                    this.SvrhaPlacanjaField = value;
                    this.RaisePropertyChanged("SvrhaPlacanja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Primalac
        {
            get
            {
                return this.PrimalacField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PrimalacField, value) != true))
                {
                    this.PrimalacField = value;
                    this.RaisePropertyChanged("Primalac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.DateTime DatumNaloga
        {
            get
            {
                return this.DatumNalogaField;
            }
            set
            {
                if ((this.DatumNalogaField.Equals(value) != true))
                {
                    this.DatumNalogaField = value;
                    this.RaisePropertyChanged("DatumNaloga");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.DateTime DatumValute
        {
            get
            {
                return this.DatumValuteField;
            }
            set
            {
                if ((this.DatumValuteField.Equals(value) != true))
                {
                    this.DatumValuteField = value;
                    this.RaisePropertyChanged("DatumValute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string RacunDuznika
        {
            get
            {
                return this.RacunDuznikaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.RacunDuznikaField, value) != true))
                {
                    this.RacunDuznikaField = value;
                    this.RaisePropertyChanged("RacunDuznika");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public double ModelZaduzenja
        {
            get
            {
                return this.ModelZaduzenjaField;
            }
            set
            {
                if ((this.ModelZaduzenjaField.Equals(value) != true))
                {
                    this.ModelZaduzenjaField = value;
                    this.RaisePropertyChanged("ModelZaduzenja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string PozivNaBrZaduzenja
        {
            get
            {
                return this.PozivNaBrZaduzenjaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PozivNaBrZaduzenjaField, value) != true))
                {
                    this.PozivNaBrZaduzenjaField = value;
                    this.RaisePropertyChanged("PozivNaBrZaduzenja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string RacunPoverioca
        {
            get
            {
                return this.RacunPoveriocaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.RacunPoveriocaField, value) != true))
                {
                    this.RacunPoveriocaField = value;
                    this.RaisePropertyChanged("RacunPoverioca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public double ModelOdobrenja
        {
            get
            {
                return this.ModelOdobrenjaField;
            }
            set
            {
                if ((this.ModelOdobrenjaField.Equals(value) != true))
                {
                    this.ModelOdobrenjaField = value;
                    this.RaisePropertyChanged("ModelOdobrenja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public double PozivNaBrOdobrenja
        {
            get
            {
                return this.PozivNaBrOdobrenjaField;
            }
            set
            {
                if ((this.PozivNaBrOdobrenjaField.Equals(value) != true))
                {
                    this.PozivNaBrOdobrenjaField = value;
                    this.RaisePropertyChanged("PozivNaBrOdobrenja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public double Iznos
        {
            get
            {
                return this.IznosField;
            }
            set
            {
                if ((this.IznosField.Equals(value) != true))
                {
                    this.IznosField = value;
                    this.RaisePropertyChanged("Iznos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string OznakaValute
        {
            get
            {
                return this.OznakaValuteField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OznakaValuteField, value) != true))
                {
                    this.OznakaValuteField = value;
                    this.RaisePropertyChanged("OznakaValute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public bool Hitno
        {
            get
            {
                return this.HitnoField;
            }
            set
            {
                if ((this.HitnoField.Equals(value) != true))
                {
                    this.HitnoField = value;
                    this.RaisePropertyChanged("Hitno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=16)]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                if ((object.ReferenceEquals(this.StatusField, value) != true))
                {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
