//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Model.XSD
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="StavkeGrupnogPlacanja", Namespace="http://schemas.datacontract.org/2004/07/Shared.Model.XSD", ItemName="Stavke")]
    public class StavkeGrupnogPlacanja : System.Collections.Generic.List<Shared.Model.XSD.StavkaGrupnogPlacanja>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StavkaGrupnogPlacanja", Namespace="http://schemas.datacontract.org/2004/07/Shared.Model.XSD")]
    public partial class StavkaGrupnogPlacanja : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDStavkeGrupnogPlacanjaField;
        
        private string IDNalogaZaPlacanjeField;
        
        private string DuznikField;
        
        private string SvrhaPlacanjaField;
        
        private string PrimalacField;
        
        private System.DateTime DatumNalogaField;
        
        private string RacunDuznikaField;
        
        private int ModelZaduzenjaField;
        
        private string PozivNaBrZaduzenjaField;
        
        private string RacunPoveriocaField;
        
        private int ModelOdobrenjaField;
        
        private string PozivNaBrOdobrenjaField;
        
        private double IznosField;
        
        private string SifraValuteField;
        
        private int IDNalogaZaGrupnoPlacanjeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDStavkeGrupnogPlacanja
        {
            get
            {
                return this.IDStavkeGrupnogPlacanjaField;
            }
            set
            {
                if ((this.IDStavkeGrupnogPlacanjaField.Equals(value) != true))
                {
                    this.IDStavkeGrupnogPlacanjaField = value;
                    this.RaisePropertyChanged("IDStavkeGrupnogPlacanja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string IDNalogaZaPlacanje
        {
            get
            {
                return this.IDNalogaZaPlacanjeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.IDNalogaZaPlacanjeField, value) != true))
                {
                    this.IDNalogaZaPlacanjeField = value;
                    this.RaisePropertyChanged("IDNalogaZaPlacanje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Duznik
        {
            get
            {
                return this.DuznikField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DuznikField, value) != true))
                {
                    this.DuznikField = value;
                    this.RaisePropertyChanged("Duznik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string SvrhaPlacanja
        {
            get
            {
                return this.SvrhaPlacanjaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SvrhaPlacanjaField, value) != true))
                {
                    this.SvrhaPlacanjaField = value;
                    this.RaisePropertyChanged("SvrhaPlacanja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Primalac
        {
            get
            {
                return this.PrimalacField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PrimalacField, value) != true))
                {
                    this.PrimalacField = value;
                    this.RaisePropertyChanged("Primalac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.DateTime DatumNaloga
        {
            get
            {
                return this.DatumNalogaField;
            }
            set
            {
                if ((this.DatumNalogaField.Equals(value) != true))
                {
                    this.DatumNalogaField = value;
                    this.RaisePropertyChanged("DatumNaloga");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string RacunDuznika
        {
            get
            {
                return this.RacunDuznikaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.RacunDuznikaField, value) != true))
                {
                    this.RacunDuznikaField = value;
                    this.RaisePropertyChanged("RacunDuznika");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int ModelZaduzenja
        {
            get
            {
                return this.ModelZaduzenjaField;
            }
            set
            {
                if ((this.ModelZaduzenjaField.Equals(value) != true))
                {
                    this.ModelZaduzenjaField = value;
                    this.RaisePropertyChanged("ModelZaduzenja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string PozivNaBrZaduzenja
        {
            get
            {
                return this.PozivNaBrZaduzenjaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PozivNaBrZaduzenjaField, value) != true))
                {
                    this.PozivNaBrZaduzenjaField = value;
                    this.RaisePropertyChanged("PozivNaBrZaduzenja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string RacunPoverioca
        {
            get
            {
                return this.RacunPoveriocaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.RacunPoveriocaField, value) != true))
                {
                    this.RacunPoveriocaField = value;
                    this.RaisePropertyChanged("RacunPoverioca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public int ModelOdobrenja
        {
            get
            {
                return this.ModelOdobrenjaField;
            }
            set
            {
                if ((this.ModelOdobrenjaField.Equals(value) != true))
                {
                    this.ModelOdobrenjaField = value;
                    this.RaisePropertyChanged("ModelOdobrenja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string PozivNaBrOdobrenja
        {
            get
            {
                return this.PozivNaBrOdobrenjaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PozivNaBrOdobrenjaField, value) != true))
                {
                    this.PozivNaBrOdobrenjaField = value;
                    this.RaisePropertyChanged("PozivNaBrOdobrenja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public double Iznos
        {
            get
            {
                return this.IznosField;
            }
            set
            {
                if ((this.IznosField.Equals(value) != true))
                {
                    this.IznosField = value;
                    this.RaisePropertyChanged("Iznos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string SifraValute
        {
            get
            {
                return this.SifraValuteField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SifraValuteField, value) != true))
                {
                    this.SifraValuteField = value;
                    this.RaisePropertyChanged("SifraValute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public int IDNalogaZaGrupnoPlacanje
        {
            get
            {
                return this.IDNalogaZaGrupnoPlacanjeField;
            }
            set
            {
                if ((this.IDNalogaZaGrupnoPlacanjeField.Equals(value) != true))
                {
                    this.IDNalogaZaGrupnoPlacanjeField = value;
                    this.RaisePropertyChanged("IDNalogaZaGrupnoPlacanje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NalogZaGrupnoPlacanje", Namespace="http://schemas.datacontract.org/2004/07/Shared.Model.XSD")]
    public partial class NalogZaGrupnoPlacanje : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDNalogaZaGrupnoPlacanjeField;
        
        private string IDPorukeField;
        
        private string SWIFTBankeDuznikaField;
        
        private string ObracunskiRacunBankeDuznikaField;
        
        private string SWIFTBankePoveriocaField;
        
        private string ObracunskiRacunBankePoveriocaField;
        
        private double UkupanIznosField;
        
        private string SifraValuteField;
        
        private System.DateTime DatumValuteField;
        
        private System.DateTime DatumField;
        
        private Shared.Model.XSD.StavkeGrupnogPlacanja StavkeGrupnogPlacanjaField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDNalogaZaGrupnoPlacanje
        {
            get
            {
                return this.IDNalogaZaGrupnoPlacanjeField;
            }
            set
            {
                if ((this.IDNalogaZaGrupnoPlacanjeField.Equals(value) != true))
                {
                    this.IDNalogaZaGrupnoPlacanjeField = value;
                    this.RaisePropertyChanged("IDNalogaZaGrupnoPlacanje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string IDPoruke
        {
            get
            {
                return this.IDPorukeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.IDPorukeField, value) != true))
                {
                    this.IDPorukeField = value;
                    this.RaisePropertyChanged("IDPoruke");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SWIFTBankeDuznika
        {
            get
            {
                return this.SWIFTBankeDuznikaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SWIFTBankeDuznikaField, value) != true))
                {
                    this.SWIFTBankeDuznikaField = value;
                    this.RaisePropertyChanged("SWIFTBankeDuznika");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ObracunskiRacunBankeDuznika
        {
            get
            {
                return this.ObracunskiRacunBankeDuznikaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ObracunskiRacunBankeDuznikaField, value) != true))
                {
                    this.ObracunskiRacunBankeDuznikaField = value;
                    this.RaisePropertyChanged("ObracunskiRacunBankeDuznika");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SWIFTBankePoverioca
        {
            get
            {
                return this.SWIFTBankePoveriocaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SWIFTBankePoveriocaField, value) != true))
                {
                    this.SWIFTBankePoveriocaField = value;
                    this.RaisePropertyChanged("SWIFTBankePoverioca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ObracunskiRacunBankePoverioca
        {
            get
            {
                return this.ObracunskiRacunBankePoveriocaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ObracunskiRacunBankePoveriocaField, value) != true))
                {
                    this.ObracunskiRacunBankePoveriocaField = value;
                    this.RaisePropertyChanged("ObracunskiRacunBankePoverioca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public double UkupanIznos
        {
            get
            {
                return this.UkupanIznosField;
            }
            set
            {
                if ((this.UkupanIznosField.Equals(value) != true))
                {
                    this.UkupanIznosField = value;
                    this.RaisePropertyChanged("UkupanIznos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string SifraValute
        {
            get
            {
                return this.SifraValuteField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SifraValuteField, value) != true))
                {
                    this.SifraValuteField = value;
                    this.RaisePropertyChanged("SifraValute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.DateTime DatumValute
        {
            get
            {
                return this.DatumValuteField;
            }
            set
            {
                if ((this.DatumValuteField.Equals(value) != true))
                {
                    this.DatumValuteField = value;
                    this.RaisePropertyChanged("DatumValute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public System.DateTime Datum
        {
            get
            {
                return this.DatumField;
            }
            set
            {
                if ((this.DatumField.Equals(value) != true))
                {
                    this.DatumField = value;
                    this.RaisePropertyChanged("Datum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public Shared.Model.XSD.StavkeGrupnogPlacanja StavkeGrupnogPlacanja
        {
            get
            {
                return this.StavkeGrupnogPlacanjaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.StavkeGrupnogPlacanjaField, value) != true))
                {
                    this.StavkeGrupnogPlacanjaField = value;
                    this.RaisePropertyChanged("StavkeGrupnogPlacanja");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
