//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Model.XSD
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PorukaOOdobrenju", Namespace="http://schemas.datacontract.org/2004/07/Shared.Model.XSD")]
    public partial class PorukaOOdobrenju : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DatumValuteField;
        
        private string IDPorukeField;
        
        private string IDPorukeNalogaField;
        
        private int IDPorukeOOdobrenjuField;
        
        private double IznosField;
        
        private string ObracunskiRacunBankePoveriocaField;
        
        private string SWIFTBankePoveriocaField;
        
        private string SifraValuteField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DatumValute
        {
            get
            {
                return this.DatumValuteField;
            }
            set
            {
                if ((this.DatumValuteField.Equals(value) != true))
                {
                    this.DatumValuteField = value;
                    this.RaisePropertyChanged("DatumValute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDPoruke
        {
            get
            {
                return this.IDPorukeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.IDPorukeField, value) != true))
                {
                    this.IDPorukeField = value;
                    this.RaisePropertyChanged("IDPoruke");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDPorukeNaloga
        {
            get
            {
                return this.IDPorukeNalogaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.IDPorukeNalogaField, value) != true))
                {
                    this.IDPorukeNalogaField = value;
                    this.RaisePropertyChanged("IDPorukeNaloga");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDPorukeOOdobrenju
        {
            get
            {
                return this.IDPorukeOOdobrenjuField;
            }
            set
            {
                if ((this.IDPorukeOOdobrenjuField.Equals(value) != true))
                {
                    this.IDPorukeOOdobrenjuField = value;
                    this.RaisePropertyChanged("IDPorukeOOdobrenju");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Iznos
        {
            get
            {
                return this.IznosField;
            }
            set
            {
                if ((this.IznosField.Equals(value) != true))
                {
                    this.IznosField = value;
                    this.RaisePropertyChanged("Iznos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObracunskiRacunBankePoverioca
        {
            get
            {
                return this.ObracunskiRacunBankePoveriocaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ObracunskiRacunBankePoveriocaField, value) != true))
                {
                    this.ObracunskiRacunBankePoveriocaField = value;
                    this.RaisePropertyChanged("ObracunskiRacunBankePoverioca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SWIFTBankePoverioca
        {
            get
            {
                return this.SWIFTBankePoveriocaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SWIFTBankePoveriocaField, value) != true))
                {
                    this.SWIFTBankePoveriocaField = value;
                    this.RaisePropertyChanged("SWIFTBankePoverioca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SifraValute
        {
            get
            {
                return this.SifraValuteField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SifraValuteField, value) != true))
                {
                    this.SifraValuteField = value;
                    this.RaisePropertyChanged("SifraValute");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
