//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8669
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Model.XSD
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PorukaOOdobrenju", Namespace="http://schemas.datacontract.org/2004/07/Shared.Model.ModeliProjekta")]
    public partial class PorukaOOdobrenju : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DatumValuteField;
        
        private string IDPorukeField;
        
        private string IDPorukeNalogaField;
        
        private int IDPorukeOOdobrenjuField;
        
        private double IznosField;
        
        private string ObracunskiRacunBankePoveriocaField;
        
        private string SWIFTBankePoveriocaField;
        
        private string SifraValuteField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DatumValute
        {
            get
            {
                return this.DatumValuteField;
            }
            set
            {
                this.DatumValuteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDPoruke
        {
            get
            {
                return this.IDPorukeField;
            }
            set
            {
                this.IDPorukeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDPorukeNaloga
        {
            get
            {
                return this.IDPorukeNalogaField;
            }
            set
            {
                this.IDPorukeNalogaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDPorukeOOdobrenju
        {
            get
            {
                return this.IDPorukeOOdobrenjuField;
            }
            set
            {
                this.IDPorukeOOdobrenjuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Iznos
        {
            get
            {
                return this.IznosField;
            }
            set
            {
                this.IznosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObracunskiRacunBankePoverioca
        {
            get
            {
                return this.ObracunskiRacunBankePoveriocaField;
            }
            set
            {
                this.ObracunskiRacunBankePoveriocaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SWIFTBankePoverioca
        {
            get
            {
                return this.SWIFTBankePoveriocaField;
            }
            set
            {
                this.SWIFTBankePoveriocaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SifraValute
        {
            get
            {
                return this.SifraValuteField;
            }
            set
            {
                this.SifraValuteField = value;
            }
        }
    }
}
