//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Model.XSD
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PorukaOZaduzenju", Namespace="http://schemas.datacontract.org/2004/07/Shared.Model.XSD")]
    public partial class PorukaOZaduzenju : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDPorukeOZaduzenjuField;
        
        private string IDPPorukeField;
        
        private string SWIFTBankeDuznikaField;
        
        private string ObracunskiRacunBankeDuznikaField;
        
        private string IDPorukeNalogaField;
        
        private System.DateTime DatumValuteField;
        
        private double IznosField;
        
        private string SifraValuteField;

		public override string ToString()
		{
			string str = "---------PORUKA-O-ZADUZENJU : [" + this.IDPorukeOZaduzenju + "]\n";
			str += "ID-PORUKE : [" + this.IDPPoruke + "]\n";
			str += "SWIFT-BANKE-DUZNIKA : [" + this.SWIFTBankeDuznika+ "]\n";
			str += "ORB-DUZNIKA : [" + this.ObracunskiRacunBankeDuznika+ "]\n";
			str += "ID-PORUKE-NALOGA : [" + this.IDPorukeNaloga + "]\n";
			str += "DATUM-VALUTE : [" + this.DatumValute+ "]\n";
			str += "IZNOS : [" + this.Iznos+ "]\n";
			str += "SIFRA-VALUTE : [" + this.SifraValute+ "]\n";

			return str;
		}

		public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDPorukeOZaduzenju
        {
            get
            {
                return this.IDPorukeOZaduzenjuField;
            }
            set
            {
                if ((this.IDPorukeOZaduzenjuField.Equals(value) != true))
                {
                    this.IDPorukeOZaduzenjuField = value;
                    this.RaisePropertyChanged("IDPorukeOZaduzenju");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string IDPPoruke
        {
            get
            {
                return this.IDPPorukeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.IDPPorukeField, value) != true))
                {
                    this.IDPPorukeField = value;
                    this.RaisePropertyChanged("IDPPoruke");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SWIFTBankeDuznika
        {
            get
            {
                return this.SWIFTBankeDuznikaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SWIFTBankeDuznikaField, value) != true))
                {
                    this.SWIFTBankeDuznikaField = value;
                    this.RaisePropertyChanged("SWIFTBankeDuznika");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ObracunskiRacunBankeDuznika
        {
            get
            {
                return this.ObracunskiRacunBankeDuznikaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ObracunskiRacunBankeDuznikaField, value) != true))
                {
                    this.ObracunskiRacunBankeDuznikaField = value;
                    this.RaisePropertyChanged("ObracunskiRacunBankeDuznika");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string IDPorukeNaloga
        {
            get
            {
                return this.IDPorukeNalogaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.IDPorukeNalogaField, value) != true))
                {
                    this.IDPorukeNalogaField = value;
                    this.RaisePropertyChanged("IDPorukeNaloga");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.DateTime DatumValute
        {
            get
            {
                return this.DatumValuteField;
            }
            set
            {
                if ((this.DatumValuteField.Equals(value) != true))
                {
                    this.DatumValuteField = value;
                    this.RaisePropertyChanged("DatumValute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public double Iznos
        {
            get
            {
                return this.IznosField;
            }
            set
            {
                if ((this.IznosField.Equals(value) != true))
                {
                    this.IznosField = value;
                    this.RaisePropertyChanged("Iznos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string SifraValute
        {
            get
            {
                return this.SifraValuteField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SifraValuteField, value) != true))
                {
                    this.SifraValuteField = value;
                    this.RaisePropertyChanged("SifraValute");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
