//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Model.XSD
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RTGSNalog", Namespace="http://schemas.datacontract.org/2004/07/Shared.Model.XSD")]
    public partial class RTGSNalog : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDRTGSNalogaField;
        
        private string IDPorukeField;
        
        private string SWIFTBankaDuznikaField;
        
        private string ObracunskiRacunBankeDuznikaField;
        
        private string SWIFTBankaPoveriocaField;
        
        private string ObracunskiRacunBankePoveriocaField;
        
        private string DuznikField;
        
        private string SvrhaPlacanjaField;
        
        private string PrimalacField;
        
        private System.DateTime DatumNalogaField;
        
        private System.DateTime DatumValuteField;
        
        private string RacunDuznikaField;
        
        private double ModelZaduzenjaField;
        
        private string PozivNaBrZaduzenjaField;
        
        private string RacunPoveriocaField;
        
        private double ModelOdobrenjaField;
        
        private string PozivNaBrOdobrenjaField;
        
        private double IznosField;
        
        private string SifraValuteField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDRTGSNaloga
        {
            get
            {
                return this.IDRTGSNalogaField;
            }
            set
            {
                if ((this.IDRTGSNalogaField.Equals(value) != true))
                {
                    this.IDRTGSNalogaField = value;
                    this.RaisePropertyChanged("IDRTGSNaloga");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string IDPoruke
        {
            get
            {
                return this.IDPorukeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.IDPorukeField, value) != true))
                {
                    this.IDPorukeField = value;
                    this.RaisePropertyChanged("IDPoruke");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SWIFTBankaDuznika
        {
            get
            {
                return this.SWIFTBankaDuznikaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SWIFTBankaDuznikaField, value) != true))
                {
                    this.SWIFTBankaDuznikaField = value;
                    this.RaisePropertyChanged("SWIFTBankaDuznika");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ObracunskiRacunBankeDuznika
        {
            get
            {
                return this.ObracunskiRacunBankeDuznikaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ObracunskiRacunBankeDuznikaField, value) != true))
                {
                    this.ObracunskiRacunBankeDuznikaField = value;
                    this.RaisePropertyChanged("ObracunskiRacunBankeDuznika");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SWIFTBankaPoverioca
        {
            get
            {
                return this.SWIFTBankaPoveriocaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SWIFTBankaPoveriocaField, value) != true))
                {
                    this.SWIFTBankaPoveriocaField = value;
                    this.RaisePropertyChanged("SWIFTBankaPoverioca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ObracunskiRacunBankePoverioca
        {
            get
            {
                return this.ObracunskiRacunBankePoveriocaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ObracunskiRacunBankePoveriocaField, value) != true))
                {
                    this.ObracunskiRacunBankePoveriocaField = value;
                    this.RaisePropertyChanged("ObracunskiRacunBankePoverioca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Duznik
        {
            get
            {
                return this.DuznikField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DuznikField, value) != true))
                {
                    this.DuznikField = value;
                    this.RaisePropertyChanged("Duznik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string SvrhaPlacanja
        {
            get
            {
                return this.SvrhaPlacanjaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SvrhaPlacanjaField, value) != true))
                {
                    this.SvrhaPlacanjaField = value;
                    this.RaisePropertyChanged("SvrhaPlacanja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Primalac
        {
            get
            {
                return this.PrimalacField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PrimalacField, value) != true))
                {
                    this.PrimalacField = value;
                    this.RaisePropertyChanged("Primalac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public System.DateTime DatumNaloga
        {
            get
            {
                return this.DatumNalogaField;
            }
            set
            {
                if ((this.DatumNalogaField.Equals(value) != true))
                {
                    this.DatumNalogaField = value;
                    this.RaisePropertyChanged("DatumNaloga");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public System.DateTime DatumValute
        {
            get
            {
                return this.DatumValuteField;
            }
            set
            {
                if ((this.DatumValuteField.Equals(value) != true))
                {
                    this.DatumValuteField = value;
                    this.RaisePropertyChanged("DatumValute");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string RacunDuznika
        {
            get
            {
                return this.RacunDuznikaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.RacunDuznikaField, value) != true))
                {
                    this.RacunDuznikaField = value;
                    this.RaisePropertyChanged("RacunDuznika");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public double ModelZaduzenja
        {
            get
            {
                return this.ModelZaduzenjaField;
            }
            set
            {
                if ((this.ModelZaduzenjaField.Equals(value) != true))
                {
                    this.ModelZaduzenjaField = value;
                    this.RaisePropertyChanged("ModelZaduzenja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string PozivNaBrZaduzenja
        {
            get
            {
                return this.PozivNaBrZaduzenjaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PozivNaBrZaduzenjaField, value) != true))
                {
                    this.PozivNaBrZaduzenjaField = value;
                    this.RaisePropertyChanged("PozivNaBrZaduzenja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string RacunPoverioca
        {
            get
            {
                return this.RacunPoveriocaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.RacunPoveriocaField, value) != true))
                {
                    this.RacunPoveriocaField = value;
                    this.RaisePropertyChanged("RacunPoverioca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public double ModelOdobrenja
        {
            get
            {
                return this.ModelOdobrenjaField;
            }
            set
            {
                if ((this.ModelOdobrenjaField.Equals(value) != true))
                {
                    this.ModelOdobrenjaField = value;
                    this.RaisePropertyChanged("ModelOdobrenja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string PozivNaBrOdobrenja
        {
            get
            {
                return this.PozivNaBrOdobrenjaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PozivNaBrOdobrenjaField, value) != true))
                {
                    this.PozivNaBrOdobrenjaField = value;
                    this.RaisePropertyChanged("PozivNaBrOdobrenja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public double Iznos
        {
            get
            {
                return this.IznosField;
            }
            set
            {
                if ((this.IznosField.Equals(value) != true))
                {
                    this.IznosField = value;
                    this.RaisePropertyChanged("Iznos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string SifraValute
        {
            get
            {
                return this.SifraValuteField;
            }
            set
            {
                if ((object.ReferenceEquals(this.SifraValuteField, value) != true))
                {
                    this.SifraValuteField = value;
                    this.RaisePropertyChanged("SifraValute");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
