//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Model.XSD
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ZahtevZaDobijanjeIzvoda", Namespace="http://schemas.datacontract.org/2004/07/Shared.Model.XSD")]
    public partial class ZahtevZaDobijanjeIzvoda : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime IDZZDIField;
        
        private string BrRacunaField;
        
        private System.Nullable<System.DateTime> DatumField;
        
        private double RedniBrPresekaField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime IDZZDI
        {
            get
            {
                return this.IDZZDIField;
            }
            set
            {
                this.IDZZDIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string BrRacuna
        {
            get
            {
                return this.BrRacunaField;
            }
            set
            {
                this.BrRacunaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<System.DateTime> Datum
        {
            get
            {
                return this.DatumField;
            }
            set
            {
                this.DatumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public double RedniBrPreseka
        {
            get
            {
                return this.RedniBrPresekaField;
            }
            set
            {
                this.RedniBrPresekaField = value;
            }
        }
    }
}
